# Generated by Django 5.0.4 on 2024-04-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(default="0", max_length=40, unique=True),
                ),
                ("data_field", models.JSONField(default=list)),
            ],
        ),
    ]
