# Generated by Django 5.0.4 on 2024-05-15 11:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('friendlyname', models.CharField(max_length=30, verbose_name='Friendly name of the Dataset')),
                ('featurenames', models.JSONField(default=list, verbose_name='Friendly feature names as a json-list')),
                ('filepath', models.FileField(upload_to='dataset/', verbose_name='Dataset as csv. First column must be target')),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal_name', models.CharField(blank=True, max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dataset', verbose_name='Dataset attached to the Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='PslResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('probas', models.JSONField(default=list)),
                ('metrics', models.JSONField(default=dict)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dataset', verbose_name='Dataset, model was calculated for')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.experiment', verbose_name='Experiment this subject is part of')),
            ],
        ),
        migrations.CreateModel(
            name='PslParam',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('_features', models.JSONField(default=list)),
                ('_scores', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='app.subject', verbose_name='Subject for which the log was created')),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(default=dict)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject', verbose_name='Subject for which the log was created')),
            ],
        ),
    ]
