# Generated by Django 5.0.4 on 2024-05-13 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_experiment_id_alter_subject_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pslparam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='app.subject', verbose_name='Subject for which the log was created'),
        ),
    ]
